version: "3"
services:
  master:
    container_name: master
    image: kataocean/jenkins_unity:2018.4.2f1
    ports:
      - 8080:8080
    volumes:
      - ./jenkins_home:/var/jenkins_home
    environment:
      - UNITY_USERNAME=${UNITY_USERNAME}
      - UNITY_PASSWORD=${UNITY_PASSWORD}
