version: "3"
services:
  master:
    container_name: master
    build:
      context: .
      dockerfile: unity.Dockerfile
      args:
        DOWNLOAD_URL: ${DOWNLOAD_URL}
        SHA1: ${SHA1}
    ports:
      - 8080:8080
    volumes:
      - ./jenkins_home:/var/jenkins_home
    environment:
      - UNITY_USERNAME=${UNITY_USERNAME}
      - UNITY_PASSWORD=${UNITY_PASSWORD}

  slave01:
    container_name: slave01
    image: jenkins/ssh-slave
    environment:
      - JENKINS_SLAVE_SSH_PUBKEY=${JENKINS_SLAVE_SSH_PUBKEY}
